### ISSUE TITLE
 Upgrade from 0.0.1 to 0.1.2

### ISSUE THREAD

**Issue by sbeckeriv** [PoiScript/tracing-newrelic#4]
Dearest maintainer,

Thank you for your work on this library. Someone before me has set it up and I am trying to update but I am running in to an issue. My old code
```rust
let layer = NewRelicLayer::new(BlockingReporter::new(&newrelic_api_token));
 let subscriber = registry::Registry::default()
             .with(LevelFilter::INFO)
            .with(tracing_subscriber::fmt::Layer::default()
            .with_ansi(false)).with(layer);

        tracing::subscriber::set_global_default(subscriber).expect("setting global default failed");
```

I fell like it should be a simple change. I now have per the example
```rust
        let newrelic = tracing_newrelic::layer(&*newrelic_api_token);
        let fmt = tracing_subscriber::fmt::layer();

        let subscriber = registry::Registry::default()
            .with(LevelFilter::INFO)
            .with(newrelic)
            .with(fmt);

        tracing::subscriber::set_global_default(subscriber).expect("setting global default failed");

```

I get this error
```rust
error[E0277]: the trait bound `NewRelicLayer: __tracing_subscriber_Layer<Layered<tracing::level_filters::LevelFilter, Registry>>` is not satisfied
    --> cli/src/bin/stctl.rs:149:19
     |
149  |             .with(newrelic)
     |              ---- ^^^^^^^^ the trait `__tracing_subscriber_Layer<Layered<tracing::level_filters::LevelFilter, Registry>>` is not implemented for `NewRelicLayer`
     |              |
     |              required by a bound introduced by this call
     |
note: required by a bound in `with`
    --> /home//.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-subscriber-0.2.25/src/layer/mod.rs:1060:12
     |
1060 |         L: Layer<Self>,
     |            ^^^^^^^^^^^ required by this bound in `with`

error[E0599]: the method `with` exists for struct `Layered<NewRelicLayer, Layered<tracing::level_filters::LevelFilter, Registry>>`, but its trait bounds were not satisfied
   --> cli/src/bin/stctl.rs:150:14
    |
150 |             .with(fmt);
    |              ^^^^ method cannot be called on `Layered<NewRelicLayer, Layered<tracing::level_filters::LevelFilter, Registry>>` due to unsatisfied trait bounds
    |
   ::: /home//.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-subscriber-0.2.25/src/layer/layered.rs:23:1
    |
23  | pub struct Layered<L, I, S = I> {
    | -------------------------------
    | |
    | doesn't satisfy `_: SubscriberExt`
    | doesn't satisfy `_: tracing::Subscriber`
    |
    = note: the following trait bounds were not satisfied:
            `Layered<NewRelicLayer, Layered<tracing::level_filters::LevelFilter, Registry>>: tracing::Subscriber`
            which is required by `Layered<NewRelicLayer, Layered<tracing::level_filters::LevelFilter, Registry>>: SubscriberExt`
            `&Layered<NewRelicLayer, Layered<tracing::level_filters::LevelFilter, Registry>>: tracing::Subscriber`
            which is required by `&Layered<NewRelicLayer, Layered<tracing::level_filters::LevelFilter, Registry>>: SubscriberExt`
            `&mut Layered<NewRelicLayer, Layered<tracing::level_filters::LevelFilter, Registry>>: tracing::Subscriber`
            which is required by `&mut Layered<NewRelicLayer, Layered<tracing::level_filters::LevelFilter, Registry>>: SubscriberExt`
```

Any advice would be appreciated. i changed the  Registry import to match the example and removed the level filter but they do not matter. I tried the target thing from the warp example as well same error.

Thanks for your time
Becker

**Comment by kylewlacy** [comment]
Based on the error message, it looks like you're using `tracing-subscriber` version 0.2.x in your `Cargo.toml`, is that right? According to this project's [`Cargo.toml`](https://github.com/PoiScript/tracing-newrelic/blob/cd02febe27de01d668040e1d4706d7fe0a510da5/Cargo.toml), it requires `tracing-subscriber` v0.3 or higher.

Can you try updating to `tracing-subscriber` v0.3? I think that should solve your issue.

**Comment by sbeckeriv** [comment]
@kylewlacy Thanks for the tip! that helped. New errors.  I got this error when I tried to run the examples as well. The MSRV is 1.58.0 when format was changed. 

error: there is no argument named `domain`
   --> /home/me/.cargo/git/checkouts/tracing-newrelic-6ff41e2a56b52fab/cd02feb/src/api.rs:288:53
    |
288 |             ApiEndpoint::Custom(domain) => format!("{domain}/log/v1"),
    |                                                     ^^^^^^^^

I need to fix this next. I am guessing another versioning issue? It looks like the Cargo.toml list version 0.11 as well?

error[E0277]: the trait bound `std::string::String: IntoUrl` is not satisfied
   --> /home/me/.cargo/git/checkouts/tracing-newrelic-6ff41e2a56b52fab/cd02feb/src/api.rs:292:19
    |
292 |             .post(url)
    |              ---- ^^^ expected an implementor of trait `IntoUrl`
    |              |
    |              required by a bound introduced by this call
    |
    = note: required because of the requirements on the impl of `IntoUrl` for `std::string::String`
note: required by a bound in `Client::post`
   --> /home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/reqwest-0.11.0/src/async_impl/client.rs:938:20
    |
938 |     pub fn post<U: IntoUrl>(&self, url: U) -> RequestBuilder {
    |                    ^^^^^^^ required by this bound in `Client::post`
help: consider borrowing here
    |
292 |             .post(&url)
    |                   +

**Comment by sbeckeriv** [comment]
cargo audit --fix upgraded the reqwest.  it looks like String was added in this version of 0.11 https://docs.rs/reqwest/0.11.2/reqwest/trait.IntoUrl.html

Thanks for help very much!
